;; kl.el --- KLambda in Elisp -*- lexical-binding: t; -*-

;; SPDX-License-Identifier: MIT

;; Author: Ethan Hawk
;; Maintainer: Ethan Hawk
;; URL: https://echawk.github.io
;; Version: 1.0.0
;; Package-Requires: ((emacs "24.1"))

;;; Commentary:

;; KLambda support in Emacs Lisp, with both an interpreter and a compiler
;; backend.

;;; Code:

(add-to-list 'load-path
             (file-name-directory (or load-file-name buffer-file-name)))

(require 'cl-lib)
(require 'ert)
(require 'ring)
(require 'subr-x)

(define-error 'kl-error "KLambda error")

(cl-defstruct (kl-stream (:constructor kl-stream-create))
  kind
  mode
  path
  buffer
  closed)

(cl-defstruct (kl-runtime (:constructor kl-runtime-create))
  globals
  functions
  types
  stdout
  stdin
  init-time
  backend)

(defconst kl-primitive-arities
  '((+ . 2) (- . 2) (* . 2) (/ . 2)
    (= . 2) (< . 2) (> . 2) (<= . 2) (>= . 2)
    (number? . 1) (integer? . 1) (string? . 1) (cons? . 1) (boolean? . 1)
    (str . 1) (n->string . 1) (string->n . 1)
    (pos . 2) (tlstr . 1) (intern . 1) (cn . 2)
    (hd . 1) (tl . 1) (cons . 2)
    (absvector . 1) (address-> . 3) (<-address . 2) (absvector? . 1)
    (open . 2) (close . 1) (pr . 2) (read-byte . 1) (write-byte . 2)
    (bound? . 1) (fn . 1)
    (simple-error . 1) (error-to-string . 1)
    (get-time . 1)
    (shen.char-stinput? . 1) (shen.char-stoutput? . 1)
    (shen.write-string . 2) (shen.read-unit-string . 1)))

(defconst kl-special-forms
  '(and cond defun do eval-kl freeze if lambda let or set thaw trap-error type value))

(defgroup kl nil
  "KLambda support in Emacs."
  :group 'languages)

(defcustom kl-default-backend 'interpreter
  "Execution backend used for new KLambda runtimes.

`interpreter' uses the defunctionalized CEK evaluator in `kl-interpreter.el'.
`compiler' compiles KL forms into Emacs Lisp closures before evaluation."
  :type '(choice (const :tag "Interpreter" interpreter)
                 (const :tag "Compiler" compiler))
  :group 'kl)

(defcustom kl-byte-compile-generated-functions t
  "When non-nil, byte-compile Emacs Lisp functions generated by the KL compiler."
  :type 'boolean
  :group 'kl)

(defcustom kl-compiler-cache-directory nil
  "When non-nil, compiler runtimes cache generated per-file installers here.

Each loaded `.kl' file can be emitted as a separate `.el' file in this
directory and reloaded on subsequent compiler-backed boots."
  :type '(choice (const :tag "Disabled" nil)
                 directory)
  :group 'kl)

(defcustom kl-byte-compile-generated-files nil
  "When non-nil, byte-compile generated KL installer files after emission."
  :type 'boolean
  :group 'kl)

(defcustom kl-compiler-interpreted-files
  '("yacc.kl" "reader.kl" "macros.kl")
  "Kernel source files that should stay on the CEK interpreter under the compiler backend.

These files make up Shen's source frontend. Keeping them on the interpreter
avoids host Lisp nesting failures while preserving compiler-backed bootstrap
and runtime performance for the rest of the kernel."
  :type '(repeat string)
  :group 'kl)

(defcustom kl-compiler-compiled-function-overrides
  '(shen.assoc->)
  "KL functions that should stay fully compiled even in interpreted frontend files."
  :type '(repeat symbol)
  :group 'kl)

(defcustom kl-repl-buffer-name "*KLambda*"
  "Name of the KLambda REPL buffer."
  :type 'string
  :group 'kl)

(defcustom kl-repl-input-ring-size 128
  "Maximum number of entries retained in KLambda REPL history."
  :type 'integer
  :group 'kl)

(defface kl-repl-prompt-face
  '((t :inherit font-lock-keyword-face :weight bold))
  "Face used for KLambda REPL prompts."
  :group 'kl)

(defvar kl--default-runtime nil)

(defvar-local kl--repl-runtime nil)
(defvar-local kl--repl-input-start nil)
(defvar-local kl--repl-input-ring nil)
(defvar-local kl--repl-history-index nil)
(defvar-local kl--repl-saved-input "")
(defvar-local kl--repl-turn 0)

(defconst kl--repl-completion-delimiters
  '(?\s ?\t ?\n ?\( ?\) ?\[ ?\] ?\{ ?\} ?\" ?\' ?\` ?, ?\;)
  "Characters that delimit KLambda tokens in the REPL.")

(defun kl--make-buffer-stream (kind mode &optional path initial-contents)
  (let ((buffer (generate-new-buffer
                 (format " *kl-%s-%s*" kind (or path mode)))))
    (when initial-contents
      (with-current-buffer buffer
        (insert initial-contents)
        (goto-char (point-min))))
    (kl-stream-create :kind kind :mode mode :path path :buffer buffer :closed nil)))

(defun kl--normalize-backend (backend)
  (pcase (or backend kl-default-backend)
    ((or 'interpreter 'compiler) (or backend kl-default-backend))
    (_ (kl--signal "Unknown KL backend %S" backend))))

(defun kl-runtime-reset (&optional stdin backend)
  (let* ((runtime (kl-runtime-create
                   :globals (make-hash-table :test 'eq)
                   :functions (make-hash-table :test 'eq)
                   :types (make-hash-table :test 'eq)
                   :stdout (kl--make-buffer-stream 'standard-output 'out)
                   :stdin (kl--make-buffer-stream 'standard-input 'in nil (or stdin ""))
                   :init-time (floor (float-time (current-time)))
                   :backend (kl--normalize-backend backend)))
         (globals (kl-runtime-globals runtime)))
    (dolist (pair
             `((*port* . "1")
               (*porters* . "Ethan Hawk")
               (*language* . "Elisp")
               (*implementation* . ,system-configuration)
               (*release* . ,emacs-version)
               (*os* . ,(symbol-name system-type))
               (*home-directory* . "")
               (*hush* . false)))
      (puthash (car pair) (cdr pair) globals))
    (puthash '*stinput* (kl-runtime-stdin runtime) globals)
    (puthash '*stoutput* (kl-runtime-stdout runtime) globals)
    (puthash '*init* (kl-runtime-init-time runtime) globals)
    runtime))

(defun kl-empty-env ()
  nil)

(defun kl-runtime-output (runtime)
  (with-current-buffer (kl-stream-buffer (kl-runtime-stdout runtime))
    (buffer-string)))

(defun kl-runtime-clear-output (runtime)
  (with-current-buffer (kl-stream-buffer (kl-runtime-stdout runtime))
    (erase-buffer)))

(defun kl-runtime-drain-output (runtime)
  (prog1 (kl-runtime-output runtime)
    (kl-runtime-clear-output runtime)))

(defun kl-runtime-set-input-string (runtime string)
  (let ((old-stream (kl-runtime-stdin runtime))
        (new-stream (kl--make-buffer-stream 'buffer-input 'in nil string)))
    (when (and (kl-stream-p old-stream)
               (buffer-live-p (kl-stream-buffer old-stream)))
      (setf (kl-stream-closed old-stream) t)
      (kill-buffer (kl-stream-buffer old-stream)))
    (setf (kl-runtime-stdin runtime) new-stream)
    (puthash '*stinput* new-stream (kl-runtime-globals runtime))
    new-stream))

(defun kl-runtime-shadow (runtime backend)
  "Return a runtime view of RUNTIME with BACKEND, sharing mutable state."
  (kl-runtime-create
   :globals (kl-runtime-globals runtime)
   :functions (kl-runtime-functions runtime)
   :types (kl-runtime-types runtime)
   :stdout (kl-runtime-stdout runtime)
   :stdin (kl-runtime-stdin runtime)
   :init-time (kl-runtime-init-time runtime)
   :backend (kl--normalize-backend backend)))

(defun kl--signal (format-string &rest args)
  (signal 'kl-error (list (apply #'format format-string args))))

(defun kl--bool (value)
  (if value 'true 'false))

(defun kl--true-p (value)
  (pcase value
    ('true t)
    ('false nil)
    (_ (kl--signal "Expected KL boolean, got %S" value))))

(defun kl--lookup-lexical (env symbol)
  (let ((cell (assq symbol env)))
    (when cell
      (cdr cell))))

(defun kl--bound-lexically-p (env symbol)
  (not (null (assq symbol env))))

(defun kl--global-bound-p (runtime symbol)
  (gethash symbol (kl-runtime-globals runtime) :kl-unbound))

(defun kl--lookup-value (runtime env symbol)
  (cond
   ((memq symbol '(true false)) symbol)
   ((kl--bound-lexically-p env symbol) (kl--lookup-lexical env symbol))
   (t symbol)))

(defun kl--resolve-function (runtime env symbol)
  (cond
   ((kl--bound-lexically-p env symbol)
    (kl--lookup-lexical env symbol))
   ((alist-get symbol kl-primitive-arities)
    `(primitive ,runtime ,symbol ,(alist-get symbol kl-primitive-arities)))
   ((gethash symbol (kl-runtime-functions runtime) nil))
   (t (kl--signal "Not applicable: %S" symbol))))

(defun kl-values-equal-p (a b)
  (equal a b))

(defun kl-value-as-string (value)
  (cond
   ((eq value 'true) "true")
   ((eq value 'false) "false")
   ((null value) "()")
   ((stringp value) value)
   ((numberp value) (number-to-string value))
   ((symbolp value) (symbol-name value))
   ((vectorp value) "#vector")
   ((consp value)
    (format "[%s]" (mapconcat #'kl-value-as-string value " ")))
   ((kl-stream-p value) "#stream")
   (t (format "%S" value))))

(defun kl-render-value (value)
  (cond
   ((stringp value) (prin1-to-string value))
   (t (kl-value-as-string value))))

(defun kl--error-to-string (err)
  (cond
   ((and (consp err) (eq (car err) 'kl-error))
    (let ((payload (cadr err)))
      (if (stringp payload)
          payload
        (error-message-string err))))
   ((and (consp err) (stringp (car err))) (car err))
   ((and (consp err) (symbolp (car err)))
    (error-message-string err))
   (t (format "%S" err))))

(defun kl--stream-open-p (stream)
  (and (kl-stream-p stream)
       (not (kl-stream-closed stream))))

(defun kl--stream-read-char (stream)
  (unless (and (kl--stream-open-p stream)
               (eq (kl-stream-mode stream) 'in))
    (kl--signal "Cannot read from %S" stream))
  (with-current-buffer (kl-stream-buffer stream)
    (if (eobp)
        -1
      (prog1 (char-after)
        (forward-char 1)))))

(defun kl--stream-write-string (stream string)
  (unless (and (kl--stream-open-p stream)
               (eq (kl-stream-mode stream) 'out))
    (kl--signal "Cannot write to %S" stream))
  (with-current-buffer (kl-stream-buffer stream)
    (goto-char (point-max))
    (insert string))
  string)

(defun kl--stream-close (stream)
  (unless (kl--stream-open-p stream)
    (kl--signal "Stream already closed"))
  (when (and (eq (kl-stream-kind stream) 'file)
             (eq (kl-stream-mode stream) 'out))
    (with-current-buffer (kl-stream-buffer stream)
      (write-region (point-min) (point-max) (kl-stream-path stream) nil 'silent)))
  (setf (kl-stream-closed stream) t)
  (when (buffer-live-p (kl-stream-buffer stream))
    (kill-buffer (kl-stream-buffer stream)))
  stream)

(defun kl--open-file-stream (path mode)
  (pcase mode
    ('in
     (with-temp-buffer
       (insert-file-contents-literally path)
       (kl--make-buffer-stream 'file 'in path (buffer-string))))
    ('out
     (kl--make-buffer-stream 'file 'out path))
    (_ (kl--signal "Unsupported open mode %S" mode))))

(defun kl--execute-primitive (runtime name args)
  (pcase name
    ('+ (apply #'+ args))
    ('- (apply #'- args))
    ('* (apply #'* args))
    ('/ (apply #'/ args))
    ('= (kl--bool (apply #'kl-values-equal-p args)))
    ('< (kl--bool (apply #'< args)))
    ('> (kl--bool (apply #'> args)))
    ('<= (kl--bool (apply #'<= args)))
    ('>= (kl--bool (apply #'>= args)))
    ('number? (kl--bool (numberp (car args))))
    ('integer? (kl--bool (and (integerp (car args)) t)))
    ('string? (kl--bool (stringp (car args))))
    ('cons? (kl--bool (consp (car args))))
    ('boolean? (kl--bool (memq (car args) '(true false))))
    ('str (kl-value-as-string (car args)))
    ('n->string (char-to-string (car args)))
    ('string->n (let ((s (car args)))
                  (if (string-empty-p s)
                      (kl--signal "empty string")
                    (aref s 0))))
    ('pos (char-to-string (aref (car args) (cadr args))))
    ('tlstr (substring (car args) 1))
    ('intern (intern (car args)))
    ('cn (concat (car args) (cadr args)))
    ('hd (car (car args)))
    ('tl (cdr (car args)))
    ('cons (cons (car args) (cadr args)))
    ('absvector (make-vector (car args) 0))
    ('address->
     (let ((vec (car args)))
       (aset vec (cadr args) (caddr args))
       vec))
    ('<-address (aref (car args) (cadr args)))
    ('absvector? (kl--bool (vectorp (car args))))
    ('open (kl--open-file-stream (car args) (cadr args)))
    ('close (kl--stream-close (car args)))
    ('pr (prog1 (car args)
           (unless (eq (kl--global-bound-p runtime '*hush*) 'true)
             (kl--stream-write-string (cadr args) (car args)))))
    ('read-byte (kl--stream-read-char (car args)))
    ('write-byte
     (prog1 (car args)
       (kl--stream-write-string (cadr args) (char-to-string (car args)))))
    ('bound? (kl--bool (not (eq (kl--global-bound-p runtime (car args)) :kl-unbound))))
    ('fn (kl--resolve-function runtime nil (car args)))
    ('simple-error (kl--signal "%s" (car args)))
    ('error-to-string (kl--error-to-string (car args)))
    ('get-time
     (pcase (car args)
       ('unix (floor (float-time (current-time))))
       ('run (- (floor (float-time (current-time)))
                (gethash '*init* (kl-runtime-globals runtime))))
       (_ (kl--signal "Unknown get-time argument %S" (car args)))))
    ('shen.char-stinput? (kl--bool (and (kl-stream-p (car args))
                                        (eq (kl-stream-kind (car args)) 'standard-input)
                                        (eq (kl-stream-mode (car args)) 'in))))
    ('shen.char-stoutput? (kl--bool (and (kl-stream-p (car args))
                                         (eq (kl-stream-mode (car args)) 'out))))
    ('shen.write-string
     (prog1 (car args)
       (kl--stream-write-string (cadr args) (car args))))
    ('shen.read-unit-string
     (let ((byte (kl--stream-read-char (car args))))
       (if (= byte -1)
           ""
         (char-to-string byte))))
    (_ (kl--signal "Unknown primitive %S" name))))

(defun kl--callable-runtime (value)
  (pcase value
    (`(closure ,runtime . ,_) runtime)
    (`(primitive ,runtime . ,_) runtime)
    (`(compiled ,runtime . ,_) runtime)
    (`(thunk ,runtime . ,_) runtime)
    (`(compiled-thunk ,runtime . ,_) runtime)
    (_ nil)))

(defun kl--apply-dispatch (fn arg)
  (cond
   ((and (consp fn) (eq (car fn) 'closure))
    (pcase fn
      (`(closure ,runtime ,params ,body ,env)
       (if (null params)
           (kl--signal "Too many arguments for %S" fn)
         (let ((new-env (cons (cons (car params) arg) env)))
           (if (null (cdr params))
               `(eval ,body ,new-env)
             `(value (closure ,runtime ,(cdr params) ,body ,new-env))))))))
   ((and (consp fn) (eq (car fn) 'primitive))
    (pcase fn
      (`(primitive ,runtime ,name ,arity . ,args)
       (let ((new-args (append args (list arg))))
         (if (= arity 1)
             `(value ,(kl--execute-primitive runtime name new-args))
           `(value (primitive ,runtime ,name ,(1- arity) . ,new-args)))))))
   ((and (consp fn) (eq (car fn) 'compiled))
    (pcase fn
      (`(compiled ,runtime ,impl ,arity . ,args)
       (let ((new-args (append args (list arg))))
         (if (= arity 1)
             `(value ,(apply impl new-args))
           `(value ,(apply #'kl-make-compiled-function runtime impl (1- arity) new-args)))))))
   (t
    (kl--signal "Not applicable: %S" fn))))

(defun kl--force-dispatch (value)
  (cond
   ((and (consp value) (eq (car value) 'closure))
    (pcase value
      (`(closure ,_runtime ,params ,body ,env)
       (if (null params)
           `(eval ,body ,env)
         `(value ,value)))))
   ((and (consp value) (eq (car value) 'primitive))
    (pcase value
      (`(primitive ,runtime ,name 0 . ,args)
       `(value ,(kl--execute-primitive runtime name args)))
      (_ `(value ,value))))
   ((and (consp value) (eq (car value) 'compiled))
    (pcase value
      (`(compiled ,_runtime ,impl 0 . ,args)
       `(value ,(apply impl args)))
      (_ `(value ,value))))
   (t
    `(value ,value))))

(defun kl-apply-function (fn args)
  (let ((value fn)
        dispatch
        callable)
    (dolist (arg args)
      (setq callable value
            dispatch (kl--apply-dispatch value arg))
      (pcase dispatch
        (`(value ,next-value)
         (setq value next-value))
        (`(eval ,next-exp ,next-env)
         (setq value (kl-eval next-exp (kl--callable-runtime callable) next-env)))))
    (setq callable value)
    (pcase (kl--force-dispatch value)
      (`(value ,next-value) next-value)
      (`(eval ,next-exp ,next-env)
       (kl-eval next-exp (kl--callable-runtime callable) next-env)))))

(require 'kl-interpreter)
(require 'kl-compiler)

(defun kl-thaw-value (value)
  (pcase value
    (`(compiled-thunk ,_runtime ,impl)
     (funcall impl))
    (_ (kl-thaw-thunk value))))

(defun kl-eval (exp &optional runtime env)
  (setq runtime (or runtime (kl-runtime-reset)))
  (setq env (or env (kl-empty-env)))
  (pcase (kl-runtime-backend runtime)
    ('interpreter (kl-interpreter-eval exp runtime env))
    ('compiler (kl-compiler-eval exp runtime env))
    (_ (kl--signal "Unknown KL backend %S" (kl-runtime-backend runtime)))))

(defun kl-read-buffer ()
  (let (forms)
    (condition-case nil
        (while t
          (push (read (current-buffer)) forms))
      (end-of-file (nreverse forms)))))

(defun kl-read-file (path)
  (with-temp-buffer
    (insert-file-contents path)
    (kl-read-buffer)))

(defun kl-load-file (path &optional runtime)
  (setq runtime (or runtime (kl-runtime-reset)))
  (if (and (eq (kl-runtime-backend runtime) 'compiler)
           kl-compiler-cache-directory)
      (kl-compiler-load-file path runtime kl-compiler-cache-directory)
    (let ((kl--compiler-current-source-file
           (and (eq (kl-runtime-backend runtime) 'compiler)
                (expand-file-name path))))
      (dolist (form (kl-read-file path))
        (kl-eval form runtime))))
  runtime)

(defun kl-load-files (paths &optional runtime)
  (setq runtime (or runtime (kl-runtime-reset)))
  (dolist (path paths runtime)
    (kl-load-file path runtime)))

(defconst kl-kernel-load-order
  '("ShenOSKernel-41.2/klambda/yacc.kl"
    "ShenOSKernel-41.2/klambda/reader.kl"
    "ShenOSKernel-41.2/klambda/writer.kl"
    "ShenOSKernel-41.2/klambda/sys.kl"
    "ShenOSKernel-41.2/klambda/dict.kl"
    "ShenOSKernel-41.2/klambda/declarations.kl"
    "ShenOSKernel-41.2/klambda/core.kl"
    "ShenOSKernel-41.2/klambda/load.kl"
    "ShenOSKernel-41.2/klambda/macros.kl"
    "ShenOSKernel-41.2/klambda/prolog.kl"
    "ShenOSKernel-41.2/klambda/sequent.kl"
    "ShenOSKernel-41.2/klambda/t-star.kl"
    "ShenOSKernel-41.2/klambda/track.kl"
    "ShenOSKernel-41.2/klambda/types.kl"
    "ShenOSKernel-41.2/klambda/toplevel.kl"
    "ShenOSKernel-41.2/klambda/extension-features.kl"
    "ShenOSKernel-41.2/klambda/extension-expand-dynamic.kl"
    "ShenOSKernel-41.2/klambda/extension-launcher.kl"
    "ShenOSKernel-41.2/klambda/extension-programmable-pattern-matching.kl"
    "ShenOSKernel-41.2/klambda/init.kl"))

(defun kl-load-kernel (&optional runtime)
  (setq runtime (or runtime (kl-runtime-reset)))
  (kl-load-files kl-kernel-load-order runtime))

(defun kl--make-runtime ()
  (kl-runtime-reset))

(defun kl--ensure-default-runtime ()
  (or kl--default-runtime
      (setq kl--default-runtime (kl--make-runtime))))

(defun kl--ensure-buffer-runtime ()
  (or kl--repl-runtime
      (setq kl--repl-runtime (kl--make-runtime))))

(defun kl--skip-read-junk ()
  (let ((moved t))
    (while moved
      (setq moved nil)
      (skip-chars-forward " \t\n\r\f")
      (when (eq (char-after) ?\;)
        (forward-line 1)
        (setq moved t)))))

(defun kl--read-string-forms (string)
  (with-temp-buffer
    (insert string)
    (goto-char (point-min))
    (let (forms)
      (condition-case nil
          (while (progn
                   (kl--skip-read-junk)
                   (not (eobp)))
            (push (read (current-buffer)) forms))
        (end-of-file
         (kl--signal "Incomplete KLambda form")))
      (nreverse forms))))

(defun kl--join-repl-output (stdout trailing-output)
  (cond
   ((string-empty-p stdout) trailing-output)
   ((string-empty-p trailing-output) stdout)
   ((string-suffix-p "\n" stdout) (concat stdout trailing-output))
   (t (concat stdout "\n" trailing-output))))

(defun kl/eval-string (string &optional runtime)
  "Evaluate STRING as KLambda input.

Return REPL-style output, including printed side effects and the final value."
  (let ((runtime (or runtime
                     (if (derived-mode-p 'kl-repl-mode)
                         (kl--ensure-buffer-runtime)
                       (kl--ensure-default-runtime))))
        result)
    (kl-runtime-clear-output runtime)
    (condition-case err
        (let ((forms (kl--read-string-forms string)))
          (dolist (form forms)
            (setq result (kl-eval form runtime)))
          (kl--join-repl-output
           (kl-runtime-drain-output runtime)
           (if forms
               (concat (kl-render-value result) "\n")
             "")))
      (error
       (kl--join-repl-output
        (kl-runtime-drain-output runtime)
        (concat (error-message-string err) "\n"))))))

(defun kl--insert-read-only (string &optional face)
  (let ((inhibit-read-only t)
        (start (point-max)))
    (goto-char (point-max))
    (insert string)
    (add-text-properties
     start (point-max)
     `(read-only t
       rear-nonsticky (read-only)
       front-sticky (read-only)
       ,@(when face `(face ,face))))))

(defun kl--prompt-string ()
  (format "%d #> " kl--repl-turn))

(defun kl--insert-prompt ()
  (kl--insert-read-only (kl--prompt-string) 'kl-repl-prompt-face)
  (set-marker kl--repl-input-start (point-max))
  (goto-char (point-max)))

(defun kl--current-input ()
  (buffer-substring-no-properties (marker-position kl--repl-input-start)
                                  (point-max)))

(defun kl--replace-current-input (string)
  (let ((inhibit-read-only t))
    (goto-char (marker-position kl--repl-input-start))
    (delete-region (marker-position kl--repl-input-start) (point-max))
    (insert string)))

(defun kl--seal-current-input ()
  (add-text-properties
   (marker-position kl--repl-input-start) (point-max)
   '(read-only t rear-nonsticky (read-only) front-sticky (read-only))))

(defun kl--completion-runtime ()
  (or kl--repl-runtime kl--default-runtime))

(defun kl--completion-token-char-p (char)
  (and char
       (not (memq char kl--repl-completion-delimiters))))

(defun kl--bounds-of-token-at-point ()
  (when (and kl--repl-input-start
             (>= (point) (marker-position kl--repl-input-start)))
    (let ((origin (point))
          (limit (marker-position kl--repl-input-start))
          start
          end)
      (save-excursion
        (while (and (> (point) limit)
                    (kl--completion-token-char-p (char-before)))
          (backward-char))
        (setq start (point))
        (goto-char origin)
        (while (kl--completion-token-char-p (char-after))
          (forward-char))
        (setq end (point)))
      (when (< start end)
        (cons start end)))))

(defun kl--completion-candidates (runtime)
  (let ((seen (make-hash-table :test 'equal))
        names)
    (dolist (symbol '(true false))
      (puthash (symbol-name symbol) t seen))
    (dolist (symbol kl-special-forms)
      (puthash (symbol-name symbol) t seen))
    (dolist (pair kl-primitive-arities)
      (puthash (symbol-name (car pair)) t seen))
    (maphash
     (lambda (symbol _value)
       (when (symbolp symbol)
         (puthash (symbol-name symbol) t seen)))
     (kl-runtime-functions runtime))
    (maphash
     (lambda (symbol _value)
       (when (symbolp symbol)
         (puthash (symbol-name symbol) t seen)))
     (kl-runtime-globals runtime))
    (maphash (lambda (name _present) (push name names)) seen)
    (sort names #'string<)))

(defun kl-repl-completion-at-point ()
  "Return completion data for the KLambda REPL input at point."
  (let ((runtime (kl--completion-runtime))
        (bounds (kl--bounds-of-token-at-point)))
    (when (and runtime bounds)
      (list (car bounds)
            (cdr bounds)
            (completion-table-dynamic
             (lambda (_prefix)
               (kl--completion-candidates runtime)))
            :exclusive 'no))))

(defun kl--record-input (input)
  (unless (string-blank-p input)
    (ring-insert kl--repl-input-ring input))
  (setq kl--repl-history-index nil
        kl--repl-saved-input ""))

(defun kl-repl-return ()
  "Evaluate the current KLambda input."
  (interactive)
  (when (< (point) (marker-position kl--repl-input-start))
    (goto-char (point-max)))
  (let* ((runtime (kl--ensure-buffer-runtime))
         (input (kl--current-input))
         (output (kl/eval-string input runtime)))
    (kl--record-input input)
    (kl--seal-current-input)
    (kl--insert-read-only "\n")
    (kl--insert-read-only output)
    (setq kl--repl-turn (1+ kl--repl-turn))
    (kl--insert-prompt)))

(defun kl-repl-previous-input ()
  "Replace current input with the previous REPL history entry."
  (interactive)
  (if (ring-empty-p kl--repl-input-ring)
      (user-error "No KLambda REPL history")
    (if kl--repl-history-index
        (when (< (1+ kl--repl-history-index) (ring-length kl--repl-input-ring))
          (setq kl--repl-history-index (1+ kl--repl-history-index)))
      (setq kl--repl-saved-input (kl--current-input)
            kl--repl-history-index 0))
    (kl--replace-current-input (ring-ref kl--repl-input-ring kl--repl-history-index))
    (goto-char (point-max))))

(defun kl-repl-next-input ()
  "Replace current input with the next REPL history entry."
  (interactive)
  (unless kl--repl-history-index
    (user-error "No newer KLambda REPL history"))
  (if (zerop kl--repl-history-index)
      (progn
        (setq kl--repl-history-index nil)
        (kl--replace-current-input kl--repl-saved-input))
    (setq kl--repl-history-index (1- kl--repl-history-index))
    (kl--replace-current-input (ring-ref kl--repl-input-ring kl--repl-history-index)))
  (goto-char (point-max)))

(defun kl-repl-beginning-of-line ()
  "Move to the start of the editable KLambda input."
  (interactive)
  (if (>= (point) (marker-position kl--repl-input-start))
      (goto-char (marker-position kl--repl-input-start))
    (move-beginning-of-line 1)))

(defun kl-repl-clear-buffer ()
  "Clear the KLambda REPL buffer, keeping the current runtime."
  (interactive)
  (let ((inhibit-read-only t))
    (erase-buffer)
    (when kl--repl-runtime
      (kl--insert-prompt))))

(defun kl-repl-reset ()
  "Reset the KLambda REPL runtime and buffer."
  (interactive)
  (let ((inhibit-read-only t))
    (erase-buffer))
  (setq kl--repl-runtime nil
        kl--repl-history-index nil
        kl--repl-saved-input ""
        kl--repl-turn 0)
  (setq kl--repl-input-ring (make-ring kl-repl-input-ring-size))
  (kl--ensure-buffer-runtime)
  (kl--insert-prompt))

(defvar kl-repl-mode-map
  (let ((map (make-sparse-keymap)))
    (set-keymap-parent map text-mode-map)
    (define-key map (kbd "RET") #'kl-repl-return)
    (define-key map (kbd "TAB") #'completion-at-point)
    (define-key map (kbd "<tab>") #'completion-at-point)
    (define-key map (kbd "M-p") #'kl-repl-previous-input)
    (define-key map (kbd "M-n") #'kl-repl-next-input)
    (define-key map (kbd "C-a") #'kl-repl-beginning-of-line)
    (define-key map (kbd "C-c C-r") #'kl-repl-reset)
    (define-key map (kbd "C-c M-o") #'kl-repl-clear-buffer)
    map))

(define-derived-mode kl-repl-mode text-mode "KLambda-REPL"
  "Major mode for interacting with a KLambda runtime."
  (setq-local indent-line-function #'ignore)
  (setq-local comment-start ";")
  (setq-local comment-end "")
  (setq-local kl--repl-input-ring (make-ring kl-repl-input-ring-size))
  (setq-local kl--repl-history-index nil)
  (setq-local kl--repl-saved-input "")
  (setq-local kl--repl-turn 0)
  (setq-local complete-at-point-functions '(kl-repl-completion-at-point))
  (setq-local kl--repl-input-start (copy-marker (point-max) nil)))

(defun kl/repl (&optional reset)
  "Open a KLambda REPL buffer.

With prefix argument RESET, reinitialize the runtime."
  (interactive "P")
  (let ((buffer (get-buffer-create kl-repl-buffer-name)))
    (pop-to-buffer buffer)
    (with-current-buffer buffer
      (unless (derived-mode-p 'kl-repl-mode)
        (kl-repl-mode))
      (when (or reset (null kl--repl-runtime))
        (kl-repl-reset))
      (goto-char (point-max)))))

(defun kl--validator-output (program)
  (with-temp-buffer
    (insert program)
    (call-process-region (point-min) (point-max)
                         (expand-file-name "bins/kl" default-directory)
                         t t nil)
    (buffer-string)))

(defun kl--validator-last-result (program)
  (let* ((output (kl--validator-output program))
         (lines (split-string output "\n" t))
         (result-line (car (last (butlast lines)))))
    (and result-line
         (string-trim
          (replace-regexp-in-string "^[0-9]+ #> " "" result-line)))))

(defmacro kl-with-runtime (bindings &rest body)
  (declare (indent 1))
  `(let* ((runtime (or ,(car bindings) (kl-runtime-reset))))
     ,@body))

(ert-deftest kl-eval-string ()
  (should (equal "3\n" (kl/eval-string "(+ 1 2)" (kl-runtime-reset)))))

(ert-deftest kl-basic-evaluation ()
  (let ((runtime (kl-runtime-reset)))
    (should (= 7 (kl-eval '(((lambda x (lambda y (+ x y))) 3) 4) runtime)))
    (should (equal '(1 2) (kl-eval '(cons 1 (cons 2 ())) runtime)))
    (should (eq 'true (kl-eval '(= (cons 1 (cons 2 ())) (cons 1 (cons 2 ()))) runtime)))
    (should (equal "a" (kl-eval '(n->string 97) runtime)))
    (should (= 65 (kl-eval '(string->n "A") runtime)))
    (should (equal "b" (kl-eval '(pos "abc" 1) runtime)))))

(ert-deftest kl-compiler-basic-evaluation ()
  (let ((runtime (kl-runtime-reset nil 'compiler)))
    (should (= 7 (kl-eval '(((lambda x (lambda y (+ x y))) 3) 4) runtime)))
    (should (equal '(1 2) (kl-eval '(cons 1 (cons 2 ())) runtime)))
    (kl-eval '(defun always () 42) runtime)
    (should (= 42 (kl-eval '(always) runtime)))))

(ert-deftest kl-compiler-preserves-lexical-cons-bindings ()
  (let ((runtime (kl-runtime-reset nil 'compiler)))
    (kl-eval '(defun singleton (X) (cons X ())) runtime)
    (should (equal '(5) (kl-eval '(singleton 5) runtime)))))

(ert-deftest kl-compiler-direct-calls-run-tail-results ()
  (let ((runtime (kl-runtime-reset nil 'compiler)))
    (kl-eval '(defun apply1 (F X) (F X)) runtime)
    (kl-eval '(defun wrap (X) (+ 1 (apply1 (lambda Y (+ Y 1)) X))) runtime)
    (should (= 7 (kl-eval '(wrap 5) runtime)))))

(ert-deftest kl-globals-and-errors ()
  (let ((runtime (kl-runtime-reset)))
    (should (= 1 (kl-eval '(set x 1) runtime)))
    (should (= 1 (kl-eval '(value x) runtime)))
    (should (eq 'true (kl-eval '(bound? x) runtime)))
    (should (string-match-p
             "boom"
             (kl-eval '(trap-error (simple-error "boom")
                                   (lambda E (error-to-string E)))
                      runtime)))))

(ert-deftest kl-zero-arg-defun ()
  (let ((runtime (kl-runtime-reset)))
    (kl-eval '(defun always () 42) runtime)
    (should (= 42 (kl-eval '(always) runtime)))))

(ert-deftest kl-loads-kernel-files ()
  (let ((runtime (kl-runtime-reset)))
    (kl-load-file "ShenOSKernel-41.2/klambda/sys.kl" runtime)
    (should (gethash 'append (kl-runtime-functions runtime)))
    (should (equal '(1 2 3)
                   (kl-eval '(append (cons 1 (cons 2 ())) (cons 3 ())) runtime)))))

(ert-deftest kl-compiler-loads-kernel-files ()
  (let ((runtime (kl-runtime-reset nil 'compiler)))
    (kl-load-file "ShenOSKernel-41.2/klambda/sys.kl" runtime)
    (should (gethash 'append (kl-runtime-functions runtime)))
    (should (equal '(1 2 3)
                   (kl-eval '(append (cons 1 (cons 2 ())) (cons 3 ())) runtime)))))

(ert-deftest kl-reads-init-kl ()
  (let ((forms (kl-read-file "ShenOSKernel-41.2/klambda/init.kl")))
    (should (consp forms))
    (should (eq 'defun (caar forms)))))

(ert-deftest kl-loads-entire-kernel-definition-set ()
  (let ((runtime (kl-runtime-reset)))
    (kl-load-kernel runtime)
    (should (gethash 'shen.initialise (kl-runtime-functions runtime)))
    (should (gethash 'shen.klfile (kl-runtime-functions runtime)))))

(ert-deftest kl-compiler-loads-entire-kernel-definition-set ()
  (let ((runtime (kl-runtime-reset nil 'compiler)))
    (kl-load-kernel runtime)
    (should (gethash 'shen.initialise (kl-runtime-functions runtime)))
    (should (gethash 'shen.klfile (kl-runtime-functions runtime)))))

(ert-deftest kl-compiler-cache-emits-per-file-installers ()
  (let* ((directory (make-temp-file "kl-compiler-cache-" t))
         (kl-compiler-cache-directory directory)
         (runtime (kl-runtime-reset nil 'compiler))
         (source "ShenOSKernel-41.2/klambda/sys.kl")
         (output (kl--compiler-output-file source directory)))
    (unwind-protect
        (progn
          (kl-load-file source runtime)
          (should (file-exists-p output))
          (should (equal '(1 2 3)
                         (kl-eval '(append (cons 1 (cons 2 ())) (cons 3 ()))
                                  runtime))))
      (delete-directory directory t))))

(ert-deftest kl-initialises-shen-runtime ()
  (let ((runtime (kl-runtime-reset)))
    (kl-load-kernel runtime)
    (kl-eval '(shen.initialise) runtime)
    (should (= 2 (kl-eval '(arity cons) runtime)))
    (should (equal "41.2" (kl-eval '(value *version*) runtime)))
    (should (eq 'false (kl-eval '(value shen.*tc*) runtime)))
    (should (= 3
               (kl-eval '(eval (cons + (cons 1 (cons 2 ()))))
                        runtime)))))

(ert-deftest kl-compiler-initialises-shen-runtime ()
  (let ((runtime (kl-runtime-reset nil 'compiler)))
    (kl-load-kernel runtime)
    (kl-eval '(shen.initialise) runtime)
    (should (= 2 (kl-eval '(arity cons) runtime)))
    (should (equal "41.2" (kl-eval '(value *version*) runtime)))
    (should (eq 'false (kl-eval '(value shen.*tc*) runtime)))
    (should (= 3
               (kl-eval '(eval (cons + (cons 1 (cons 2 ()))))
                        runtime)))))

(ert-deftest kl-validator-compatibility ()
  (skip-unless (file-executable-p (expand-file-name "bins/kl" default-directory)))
  (let ((runtime (kl-runtime-reset)))
    (dolist (expr '("(+ 1 2)"
                    "(n->string 97)"
                    "(string->n \"A\")"
                    "(pos \"abc\" 1)"
                    "(trap-error (simple-error \"x\") (lambda E (error-to-string E)))"
                    "(set x 1)\n(value x)"
                    "(= (cons 1 (cons 2 ())) (cons 1 (cons 2 ())))"))
      (let* ((forms (with-temp-buffer
                      (insert expr)
                      (goto-char (point-min))
                      (kl-read-buffer)))
             result)
        (setq runtime (kl-runtime-reset))
        (dolist (form forms)
          (setq result (kl-eval form runtime)))
        (should (equal (kl-render-value result)
                       (kl--validator-last-result expr)))))))

(ert-deftest kl-repl-return-prints-result ()
  (with-temp-buffer
    (kl-repl-mode)
    (setq kl--repl-runtime (kl-runtime-reset))
    (kl--insert-prompt)
    (goto-char (point-max))
    (insert "(+ 1 2)")
    (kl-repl-return)
    (should (string-match-p (regexp-quote "\n3\n")
                            (buffer-string)))
    (should (string-suffix-p "1 #> " (buffer-string)))))

(ert-deftest kl-repl-completion-at-point-offers-runtime-symbols ()
  (with-temp-buffer
    (kl-repl-mode)
    (setq kl--repl-runtime (kl-runtime-reset))
    (kl-eval '(defun always () 42) kl--repl-runtime)
    (insert "(alw")
    (set-marker kl--repl-input-start (point-min))
    (goto-char (point-max))
    (pcase-let ((`(,start ,end ,table . ,_) (kl-repl-completion-at-point)))
      (should (equal "alw"
                     (buffer-substring-no-properties start end)))
      (should (member "always"
                      (all-completions "alw" table))))))

(ert-deftest kl-repl-history-navigation ()
  (with-temp-buffer
    (kl-repl-mode)
    (setq kl--repl-runtime (kl-runtime-reset))
    (kl--insert-prompt)
    (goto-char (point-max))
    (insert "(+ 1 2)")
    (kl-repl-return)
    (insert "(* 2 3)")
    (kl-repl-return)
    (kl-repl-previous-input)
    (should (equal "(* 2 3)" (kl--current-input)))
    (kl-repl-previous-input)
    (should (equal "(+ 1 2)" (kl--current-input)))
    (kl-repl-next-input)
    (should (equal "(* 2 3)" (kl--current-input)))
    (kl-repl-next-input)
    (should (equal "" (kl--current-input)))))

(provide 'kl)

;;; kl.el ends here
